{
 "title": "Server Monitoring Dashboard",
 "description": "Dashboard to view multiple servers",
 "tags": [ "prometheus" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(node_exporter_build_info, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "$node",
   "type": "stat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 0 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"system\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"system\",job=~'$node'}[5m]))",
     "legendFormat": "system"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"user\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"user\",job=~'$node'}[5m]))",
     "legendFormat": "user"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"nice\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"nice\",job=~'$node'}[5m]))",
     "legendFormat": "nice"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"iowait\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"iowait\",job=~'$node'}[5m]))",
     "legendFormat": "iowait"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"steal\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"steal\",job=~'$node'}[5m]))",
     "legendFormat": "steal"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"idle\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"idle\",job=~'$node'}[5m]))",
     "legendFormat": "idle"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"irq\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"irq\",job=~'$node'}[5m]))",
     "legendFormat": "irq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"softirq\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"softirq\",job=~'$node'}[5m]))",
     "legendFormat": "softirq"
    },
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode=\"guest\",job=~'$node'}[5m])) or sum(irate(node_cpu{mode=\"guest\",job=~'$node'}[5m]))",
     "legendFormat": "guest"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "( node_memory_MemTotal_bytes{job=~'$node'} - node_memory_MemFree_bytes{job=~'$node'} - node_memory_Buffers_bytes{job=~'$node'} - node_memory_Cached_bytes{job=~'$node'} - node_memory_SwapCached_bytes{job=~'$node'} - node_memory_Slab_bytes{job=~'$node'} - node_memory_PageTables_bytes{job=~'$node'} - node_memory_VmallocUsed_bytes{job=~'$node'} ) or ( node_memory_MemTotal{job=~'$node'} - node_memory_MemFree{job=~'$node'} - node_memory_Buffers{job=~'$node'} - node_memory_Cached{job=~'$node'} - node_memory_SwapCached{job=~'$node'} - node_memory_Slab{job=~'$node'} - node_memory_PageTables{job=~'$node'} - node_memory_VmallocUsed{job=~'$node'} )",
     "legendFormat": "Apps"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=~'$node'} or node_memory_Buffers{job=~'$node'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=~'$node'} or node_memory_Cached{job=~'$node'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=~'$node'} or node_memory_MemFree{job=~'$node'}",
     "legendFormat": "Free"
    },
    {
     "expr": "node_memory_Slab_bytes{job=~'$node'} or node_memory_Slab{job=~'$node'}",
     "legendFormat": "Slab"
    },
    {
     "expr": "node_memory_SwapCached_bytes{job=~'$node'} or node_memory_SwapCached{job=~'$node'}",
     "legendFormat": "SwapCached"
    },
    {
     "expr": "node_memory_PageTables_bytes{job=~'$node'} or node_memory_PageTables{job=~'$node'}",
     "legendFormat": "PageTables"
    },
    {
     "expr": "node_memory_VmallocUsed_bytes{job=~'$node'} or node_memory_VmallocUsed{job=~'$node'}",
     "legendFormat": "VmallocUsed"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{job=~'$node'} - node_memory_SwapFree{job=~'$node'}) or (node_memory_SwapTotal{job=~'$node'} - node_memory_SwapFree{job=~'$node'})",
     "legendFormat": "Swap"
    },
    {
     "expr": "node_memory_Committed_AS_bytes{job=~'$node'} or node_memory_Committed_AS{job=~'$node'}",
     "legendFormat": "Committed"
    },
    {
     "expr": "node_memory_Mapped_bytes{job=~'$node'} or node_memory_Mapped{job=~'$node'}",
     "legendFormat": "Mapped"
    },
    {
     "expr": "node_memory_Active_bytes{job=~'$node'} or node_memory_Active{job=~'$node'}",
     "legendFormat": "Active"
    },
    {
     "expr": "node_memory_Inactive_bytes{job=~'$node'} or node_memory_Inactive{job=~'$node'}",
     "legendFormat": "Inactive"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=~\"$node\"}",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail_bytes{job=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{job=~'$node',device !~'tmpfs',device!~'by-uuid'}) or 100.0 - 100 * (node_filesystem_avail{job=~'$node',device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{job=~'$node',device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=~'$node'}[5m])*8 or irate(node_network_receive_bytes{job=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_in"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=~'$node'}[5m])*8 or irate(node_network_transmit_bytes{job=~'$node'}[5m])*8",
     "legendFormat": "{{device}}_out"
    }
   ]
  }
 ]
}