# global:

route:
  receiver: 'admin'
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  group_by: ['instance', 'severity']

receivers:
- name: 'admin'

  email_configs:
    # - send_resolved: true
    - to: 'fb.gerami@gmail.com'
      from: 'fb.gerami@gmail.com'
      # resolve_timeout: 1m
      smarthost: smtp.gmail.com:587
      auth_username: 'fb.gerami@gmail.com'
      auth_password: '####'
      auth_identity: 'fb.gerami@gmail.com'
  telegram_configs:
    - bot_token: '7437692482:AAGMCsDvIFcbZxGNhX8PR3CmDbV-rUh9c14'
      api_url: "https://api.telegram.org"
      chat_id: -4213859099
      parse_mode: ""
      send_resolved: true
      disable_notifications: false
      http_config:
        proxy_url: 'https://preschool.hadihoda.com/PEF6giDNzvUJLYOT/1c74fbcf-e7f8-46e0-ae63-d9b5dc32a987/#gerami'
        follow_redirects: true
        enable_http2: true
